### ISSUE TITLE
Release 1.0.1

### ISSUE THREAD

**Issue by tjarvstrand** [nickolas-pohilets/flutter-localized-countries#3]
Hi!

Thanks for a very useful package!

Could we get a release of `1.0.1` to pub.dev? :)

Right now I have to override the `intl` version. Not a biggie but it would still be nice to remove it.

Thanks!

**Comment by SpiegelSoft** [comment]
I didn't know how to override dependencies. If anyone else has the same issue before v1.0.1 comes out, you can do this in `pubspec.yaml`:

```
dependency_overrides:
  intl: ^0.16.0
```
